### ISSUE TITLE
Out of memory error

### ISSUE THREAD

**Issue by trankchung** [GGP1/kure#5]
Kure is throwing OOM error below even though I have lots of memory.
```
$ free -m
              total        used        free      shared  buff/cache   available
Mem:           3933        3554         103           0         275        1313
Swap:          1024         397         626
```

```
$ kure ls
Enter master password: 
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0xac392f, 0x16)
        C:/Program Files/Go/src/runtime/panic.go:1117 +0x72
runtime.sysMap(0xc004000000, 0x40000000, 0xf5c8f0)
        C:/Program Files/Go/src/runtime/mem_linux.go:169 +0xc6
runtime.(*mheap).sysAlloc(0xf43800, 0x40000000, 0x42bf97, 0xf43808)
        C:/Program Files/Go/src/runtime/malloc.go:729 +0x1e5
runtime.(*mheap).grow(0xf43800, 0x20000, 0x0)
        C:/Program Files/Go/src/runtime/mheap.go:1346 +0x85
runtime.(*mheap).allocSpan(0xf43800, 0x20000, 0xc000190100, 0x7f8cc1891668)
        C:/Program Files/Go/src/runtime/mheap.go:1173 +0x609
runtime.(*mheap).alloc.func1()
        C:/Program Files/Go/src/runtime/mheap.go:910 +0x59
runtime.systemstack(0x0)
        C:/Program Files/Go/src/runtime/asm_amd64.s:379 +0x66
runtime.mstart()
        C:/Program Files/Go/src/runtime/proc.go:1246

goroutine 1 [running]:
runtime.systemstack_switch()
        C:/Program Files/Go/src/runtime/asm_amd64.s:339 fp=0xc0001237e0 sp=0xc0001237d8 pc=0x46a7a0
runtime.(*mheap).alloc(0xf43800, 0x20000, 0xc000120101, 0x40d42a)
        C:/Program Files/Go/src/runtime/mheap.go:904 +0x85 fp=0xc000123830 sp=0xc0001237e0 pc=0x427c45
runtime.(*mcache).allocLarge(0x7f8ce86eba68, 0x40000000, 0xc0001b0101, 0x7f8cc1891668)
        C:/Program Files/Go/src/runtime/mcache.go:224 +0x97 fp=0xc000123888 sp=0xc000123830 pc=0x4182b7
runtime.mallocgc(0x40000000, 0x9f9960, 0x1, 0xc0001be000)
        C:/Program Files/Go/src/runtime/malloc.go:1078 +0x925 fp=0xc000123910 sp=0xc000123888 pc=0x40dee5
runtime.makeslice(0x9f9960, 0x100000, 0x100000, 0xe3936e4be40b3259)
        C:/Program Files/Go/src/runtime/slice.go:98 +0x6c fp=0xc000123940 sp=0xc000123910 pc=0x44df6c
golang.org/x/crypto/argon2.initBlocks(0xc0001ba000, 0x800100000, 0x29, 0xc0000feabd, 0x20)
        F:/Gasti/Go/pkg/mod/golang.org/x/crypto@v0.0.0-20210220033148-5ea612d1eb83/argon2/argon2.go:160 +0x59 fp=0xc0001239a0 sp=0xc000123940 pc=0x803239
golang.org/x/crypto/argon2.deriveKey(0x2, 0x7f8cc188ffd7, 0x29, 0x29, 0xc0000feabd, 0x20, 0x20, 0x0, 0x0, 0x0, ...)
        F:/Gasti/Go/pkg/mod/golang.org/x/crypto@v0.0.0-20210220033148-5ea612d1eb83/argon2/argon2.go:115 +0x1dc fp=0xc000123a90 sp=0xc0001239a0 pc=0x802cfc
golang.org/x/crypto/argon2.IDKey(...)
        F:/Gasti/Go/pkg/mod/golang.org/x/crypto@v0.0.0-20210220033148-5ea612d1eb83/argon2/argon2.go:99
github.com/GGP1/kure/crypt.deriveKey(0xc0000feabd, 0x20, 0x20, 0x1, 0x1, 0x4, 0x4, 0x1, 0x0)
        F:/Gasti/Go/src/github.com/GGP1/kure/crypt/crypt.go:123 +0x2a6 fp=0xc000123b68 sp=0xc000123a90 pc=0x809086
github.com/GGP1/kure/crypt.Decrypt(0xc0000fea81, 0x5c, 0x5c, 0x5c, 0x10000000000001, 0x100000008, 0x0, 0x0)
        F:/Gasti/Go/src/github.com/GGP1/kure/crypt/crypt.go:68 +0x9c fp=0xc000123c30 sp=0xc000123b68 pc=0x808a3c
github.com/GGP1/kure/auth.Login.func1(0xc000200500, 0xf5a4b0, 0x0, 0x0, 0x0, 0x0)
        F:/Gasti/Go/src/github.com/GGP1/kure/auth/auth.go:63 +0x18f fp=0xc000123ce0 sp=0xc000123c30 pc=0x918baf
github.com/spf13/cobra.(*Command).execute(0xc000200500, 0xf5a4b0, 0x0, 0x0, 0xc000200500, 0xf5a4b0)
        F:/Gasti/Go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:841 +0x523 fp=0xc000123da0 sp=0xc000123ce0 pc=0x904303
github.com/spf13/cobra.(*Command).ExecuteC(0xeafc40, 0xaebed0, 0xb7c898, 0xb6ad20)
        F:/Gasti/Go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x375 fp=0xc000123e80 sp=0xc000123da0 pc=0x904dd5
github.com/spf13/cobra.(*Command).Execute(...)
        F:/Gasti/Go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
github.com/GGP1/kure/commands/root.Execute(0xc000152200, 0xc000152200, 0xc000000180)
        F:/Gasti/Go/src/github.com/GGP1/kure/commands/root/root.go:41 +0x3b fp=0xc000123eb0 sp=0xc000123e80 pc=0x98d51b
main.main()
        F:/Gasti/Go/src/github.com/GGP1/kure/main.go:33 +0x1b3 fp=0xc000123f88 sp=0xc000123eb0 pc=0x98e873
runtime.main()
        C:/Program Files/Go/src/runtime/proc.go:225 +0x256 fp=0xc000123fe0 sp=0xc000123f88 pc=0x438bd6
runtime.goexit()
        C:/Program Files/Go/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc000123fe8 sp=0xc000123fe0 pc=0x46c4a1

goroutine 18 [sleep]:
time.Sleep(0x1dcd6500)
        C:/Program Files/Go/src/runtime/time.go:193 +0xd2
github.com/awnumar/memguard/core.NewCoffer.func1(0xc0000a0240)
        F:/Gasti/Go/pkg/mod/github.com/awnumar/memguard@v0.22.2/core/coffer.go:43 +0x2a
created by github.com/awnumar/memguard/core.NewCoffer
        F:/Gasti/Go/pkg/mod/github.com/awnumar/memguard@v0.22.2/core/coffer.go:40 +0xd6

goroutine 5 [syscall]:
os/signal.signal_recv(0x0)
        C:/Program Files/Go/src/runtime/sigqueue.go:168 +0xa5
os/signal.loop()
        C:/Program Files/Go/src/os/signal/signal_unix.go:23 +0x25
created by os/signal.Notify.func1.1
        C:/Program Files/Go/src/os/signal/signal.go:151 +0x45

goroutine 20 [chan receive]:
github.com/GGP1/kure/sig.(*sig).Listen.func1(0xf2ae20, 0xc000152200)
        F:/Gasti/Go/src/github.com/GGP1/kure/sig/sig.go:69 +0x4c
created by github.com/GGP1/kure/sig.(*sig).Listen
        F:/Gasti/Go/src/github.com/GGP1/kure/sig/sig.go:68 +0xfd
```

**Comment by GGP1** [comment]
Thanks for reporting, the program ran out of memory when **argon2 is deriving the key** (CPU and memory costs could be really high depending on the parameters passed), using higher resources than you computer is allowed to may be the cause of the problem. Is this happening multiple times? Could you share the output of the `kure config argon2` command and memory specs of your computer?

**Comment by trankchung** [comment]
```
$ kure config argon2               
Iterations: 1
Memory: 1048576
Threads: 8
```

My computer is a Lenovo i5 with 16G of RAM and Intel Graphic 620.

I'm getting this error inside of WSL2 though. I'm not sure if it matters.

**Comment by GGP1** [comment]
Please check how much time it takes for you to execute the following command: `kure config argon2 test -m 1048576 -i 1 -t 8`. If it takes too long it, the argon2 parameters are too high for your PC (I ran Kure in a laptop with similar specs and I had to lower them). If you are getting the error inside **WSL2** only it may be because you are really close to the limit and once you consume more memory it fails.

**Comment by trankchung** [comment]
My 20 results below. Do I need to change?

```
$ for i in {1..20}; do kure config argon2 test -m 1048576 -i 1 -t 8; done    
1.3527213s
1.7364784s
1.1930056s
1.2435871s
1.1611317s
1.4666272s
1.4788757s
1.5648912s
1.7092158s
1.8670249s
1.5594141s
1.5210478s
1.4449551s
1.4617272s
1.3973243s
1.5229399s
1.6960213s
1.4538034s
1.578756s
1.5762712s
```

**Comment by GGP1** [comment]
Yes, I'd suggest reducing the **memory** value, you can do it with the `kure restore` command. It will re-encrypt all the records with the new credentials, use the same master password. Before doing that it's possible to test the parameters that you are going to use with `kure config argon2 test` and its flags.
